export const watchedClubs = [
    // Premier League
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton",
    "Chelsea",
    "Coventry",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Hull City",
    "Ipswich",
    "Leeds",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle",
    "Nottingham Forest",
    "Sunderland",
    "Tottenham",
    // La Liga
    "Barcelona",
    "Real Madrid",
    "Atlético Madrid",
    // "Valencia",
    "Sevilla",
    // "Villarreal",
    "Real Betis",
    // "Real Sociedad",
    // "Athletic Bilbao",
    // "Celta Vigo",
    // "Getafe",
    // "Rayo Vallecano",
    // "Las Palmas",
    // "Granada",
    // "Osasuna",
    // "Girona",
    // "Alavés",
    // "Mallorca",
    // "Cádiz",
    // Serie A
    "Inter",
    "AC Milan",
    "Juventus",
    "Napoli",
    "AS Roma",
    "Como",
    // "Lazio",
    // "Atalanta",
    // "Fiorentina",
    // "Torino",
    // "Bologna",
    // "Monza",
    // "Genoa",
    // "Lecce",
    // "Udinese",
    // "Hellas Verona",
    // "Parma",
    // "Cagliari",
    //"Sassuolo",
    // Ligue 1
    "Paris Saint Germain",
    "Marseille",
    // "Lyon",
    "Monaco",
    // "Nice",
    // "Rennes",
    // "Lille",
    "Lens",
    // "Saint-Étienne",
    // "Nantes",
    // "Bordeaux",
    // "Montpellier",
    // "Strasbourg",
    // "Toulouse",
    // "Brest",
    // "Angers",
    // "Reims",
    // " Metz",
    // "Amiens",
    // "Ajaccio",
    // Bundesliga
    "Bayern München",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    // "Borussia Mönchengladbach",
    // "Eintracht Frankfurt",
    // "Schalke 04",
    // "1899 Hoffenheim",
    // "1. FC Köln",
    // "VfB Stuttgart",
    // "Hertha BSC",
    // "Werder Bremen",
    // "FC Augsburg",
    // "FSV Mainz 05",
    // "Freiburg",
    // "Union Berlin",
    // "Bochum",
    // "Arminia Bielefeld",
    // "Greuther Fürth",
    // "Turkish Liga"
    "Galatasaray",
    "Fenerbahçe"
];

// SERIE A:  AC Milan, Atalanta, Bologna, Cagliari, Como, Fiorentina, Frosinone, Genoa, Inter, Juventus, Lazio, Lecce, Monza, Napoli, Parma, AS Roma, Sassuolo, Torino, Udinese, Venezia 



// BUNDESLIGA: Borussia Mönchengladbach, Bayer Leverkusen, SC Freiburg, VfB Stuttgart, FSV Mainz 05, Union Berlin, 1899 Hoffenheim, FC Augsburg, Werder Bremen, RB Leipzig, Borussia Dortmund, Eintracht Frankfurt, Bayern München -- FC Schalke 04 , SV Elversberg , and SC Paderborn 07



// PREMIER LEAGUE: Manchester United, Fulham, Ipswich, Liverpool, Newcastle, Arsenal, Everton, Brighton, Nottingham Forest, Bournemouth, Aston Villa, Brentford, Crystal Palace, Chelsea, Manchester City, Tottenham, ---Sunderland, Coventry, Hull, Leeds 



// LA LIGA: Athletic Club, Getafe, Real Betis, Celta Vigo, Alaves, Las Palmas, Sevilla, Osasuna, Leganes, Valencia, Barcelona, Real Sociedad, Rayo Vallecano, Real Madrid, Valladolid, Espanyol, Villarreal, Atletico Madrid --- Deportivo La Coruña , Elche CF , Levante UD , Málaga CF , and Racing Santander

export const watchedCountries = [
    // "Austria",
    "Belgium",
    // "Bosnia and Herzegovina",
    "Croatia",
    // "Czechia",
    "England",
    "France",
    "Germany",
    "Netherlands",
    "Norway",
    "Portugal",
    "Scotland",
    "Spain",
    "Sweden",
    "Switzerland",
    "Türkiye",
    "Argentina",
    "Brazil",
    "Colombia",
    "Ecuador",
    // "Paraguay",
    "Uruguay",
    // "Curaçao",
    // "Haiti",
    // "Panama",
    // "New Zealand",
    "Nigeria",
    // Nigeria,
    "Algeria",
    "Cape Verde",
    "DR Congo",
    "Ivory Coast",
    "Egypt",
    "Ghana",
    "Morocco",
    "Senegal",
    "South Africa",
    // "Tunisia",
    // "Australia",
    // "Iraq",
    // "Iran",
    "Japan",
    // "Jordan",
    "South Korea",
    // "Qatar",
    // "Saudi Arabia",
    // "Uzbekistan",
    // "Canada",
    "Mexico",
    // "United States"
];

export const clubNamebyID = {
  // Premier League
  "42": "Arsenal",
  "66": "Aston Villa",
  "35": "Bournemouth",
  "55": "Brentford",
  "51": "Brighton",
  "49": "Chelsea",
  "1346": "Coventry",
  "52": "Crystal Palace",
  "45": "Everton",
  "36": "Fulham",
  "64": "Hull",
  "57": "Ipswich",
  "63": "Leeds",
  "40": "Liverpool",
  "50": "Man City",
  "33": "Man Utd",
  "34": "Newcastle",
  "65": "Nottingham",
  "746": "Sunderland",
  "47": "Tottenham",

  // La Liga
  "529": "Barcelona",
  "541": "Real Madrid",
  "530": "Atletico Madrid",
  "536": "Sevilla",
  "543": "Betis",

  // Serie A
  "505": "Inter",
  "489": "Milan",
  "496": "Juventus",
  "492": "Napoli",
  "497": "Roma",
  "895": "Como",

  // Ligue 1
  "85": "PSG",
  "81": "Marseille",
  "80": "Lyon",
  "91": "Monaco",
  "116": "Lens",

  // Bundesliga
  "157": "Bayern Munich",
  "165": "Borussia Dortmund",
  "173": "RB Leipzig",
  "168": "Bayer Leverkusen",

  // Turkish Süper Lig
  "645": "Galatasaray",
  "611": "Fenerbahce",

  // National Teams
  "1": "Belgium",
  "2": "France",
  "3": "Croatia",
  "4": "Russia",
  "5": "Sweden",
  "6": "Brazil",
  "7": "Uruguay",
  "8": "Colombia",
  "9": "Spain",
  "10": "England",
  "11": "Panama",
  "12": "Japan",
  "13": "Senegal",
  "14": "Serbia",
  "15": "Switzerland",
  "16": "Mexico",
  "17": "South Korea",
  "18": "Iceland",
  "19": "Nigeria",
  "20": "Australia",
  "21": "Denmark",
  "22": "Iran",
  "23": "Saudi Arabia",
  "24": "Poland",
  "25": "Germany",
  "26": "Argentina",
  "27": "Portugal",
  "28": "Tunisia",
  "29": "Costa Rica",
  "30": "Peru",
  "31": "Morocco",
  "32": "Egypt"
};

/* COUNTRY: Belgium -1, France -2, Croatia -3, Russia -4, Sweden -5, Brazil -6, Uruguay -7, Colombia -8, Spain -9, England -10, Panama -11, Japan -12, Senegal -13, Serbia -14, Switzerland -15, Mexico -16, South Korea -17, Iceland -18, Nigeria -19, Australia -20, Denmark -21, Iran -22, Saudi Arabia -23, Poland -24, Germany -25, Argentina -26, Portugal -27, Tunisia -28, Costa Rica -29, Peru -30, Morocco -31, Egypt -32, 

PREM: Manchester United -33, Newcastle -34, Fulham -36, Liverpool -40, Everton -45, Tottenham -47, Chelsea -49, Manchester City -50, Crystal Palace -52, Ipswich -57, Leeds -63, Hull City -64, Nottingham Forest -65, --coventry, --sunderland 

SPAIN: Barcelona -529, Real Madrid -541, Atletico Madrid -530, Sevilla -536,  Real Betis -543, 

ITALY:  Inter -505, AC Milan -489, Juventus -496, Napoli -492, AS Roma -497, Como -895, 

FRANCE: Paris Saint Germain -85, Marseille -81, Lyon -80, Monaco -91, Lens -116, 

GERMANY: Bayern München -157, Borussia Dortmund -165, RB Leipzig -173, Bayer Leverkusen -168, 

TURKEY:

*/