export const watchedClubs = [
    // Premier League
    "Arsenal",
    "Aston Villa",
    "AFC Bournemouth",
    "Brentford",
    "Brighton & Hove Albion",
    "Chelsea",
    "Coventry City",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Hull City",
    "Ipswich Town",
    "Leeds United",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle United",
    "Nottingham Forest",
    "Sunderland",
    "Tottenham Hotspur",
    // La Liga
    "Barcelona",
    "Real Madrid",
    "Atlético Madrid",
    "Valencia",
    "Sevilla",
    "Villarreal",
    "Real Betis",
    "Real Sociedad",
    "Athletic Bilbao",
    "Celta Vigo",
    "Getafe",
    "Rayo Vallecano",
    "Las Palmas",
    "Granada",
    "Osasuna",
    "Girona",
    "Alavés",
    "Mallorca",
    "Cádiz",
    // Serie A
    "Inter Milan",
    "AC Milan",
    "Juventus",
    "Napoli",
    "Roma",
    "Lazio",
    "Atalanta",
    "Fiorentina",
    "Torino",
    "Bologna",
    "Monza",
    "Genoa",
    "Lecce",
    "Udinese",
    "Hellas Verona",
    "Parma",
    "Cagliari",
    "Empoli",
    "Sassuolo",
    // Ligue 1
    "Paris Saint-Germain",
    "Marseille",
    "Lyon",
    "Monaco",
    "Nice",
    "Rennes",
    "Lille",
    "Lens",
    "Saint-Étienne",
    "Nantes",
    "Bordeaux",
    "Montpellier",
    "Strasbourg",
    "Toulouse",
    "Brest",
    "Angers",
    "Reims",
    " Metz",
    "Amiens",
    "Ajaccio",
    // Bundesliga
    "Bayern Munich",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    "Borussia Mönchengladbach",
    "Eintracht Frankfurt",
    "Schalke 04",
    "1. FC Köln",
    "VfB Stuttgart",
    "Hertha BSC",
    "Werder Bremen",
    "FC Augsburg",
    "Mainz 05",
    "Freiburg",
    "Union Berlin",
    "Bochum",
    "Arminia Bielefeld",
    "Greuther Fürth"
];

export const watchedCountries = [
    "Austria",
    "Belgium",
    "Bosnia and Herzegovina",
    "Croatia",
    "Czechia",
    "England",
    "France",
    "Germany",
    "Netherlands",
    "Norway",
    "Portugal",
    "Scotland",
    "Spain",
    "Sweden",
    "Switzerland",
    "Türkiye",
    "Argentina",
    "Brazil",
    "Colombia",
    "Ecuador",
    "Paraguay",
    "Uruguay",
    "Curaçao",
    "Haiti",
    "Panama",
    "New Zealand",
    "Algeria",
    "Cape Verde",
    "DR Congo",
    "Ivory Coast",
    "Egypt",
    "Ghana",
    "Morocco",
    "Senegal",
    "South Africa",
    "Tunisia",
    "Australia",
    "Iraq",
    "Iran",
    "Japan",
    "Jordan",
    "South Korea",
    "Qatar",
    "Saudi Arabia",
    "Uzbekistan",
    "Canada",
    "Mexico",
    "United States"
];
