export const watchedClubs = [
    // Premier League
    "Arsenal",
    "Aston Villa",
    "Bournemouth",
    "Brentford",
    "Brighton",
    "Chelsea",
    "Coventry",
    "Crystal Palace",
    "Everton",
    "Fulham",
    "Hull City",
    "Ipswich",
    "Leeds",
    "Liverpool",
    "Manchester City",
    "Manchester United",
    "Newcastle",
    "Nottingham Forest",
    "Sunderland",
    "Tottenham",
    // La Liga
    "Barcelona",
    "Real Madrid",
    "Atlético Madrid",
    // "Valencia",
    "Sevilla",
    // "Villarreal",
    "Real Betis",
    // "Real Sociedad",
    // "Athletic Bilbao",
    // "Celta Vigo",
    // "Getafe",
    // "Rayo Vallecano",
    // "Las Palmas",
    // "Granada",
    // "Osasuna",
    // "Girona",
    // "Alavés",
    // "Mallorca",
    // "Cádiz",
    // Serie A
    "Inter",
    "AC Milan",
    "Juventus",
    "Napoli",
    "AS Roma",
    "Como",
    // "Lazio",
    // "Atalanta",
    // "Fiorentina",
    // "Torino",
    // "Bologna",
    // "Monza",
    // "Genoa",
    // "Lecce",
    // "Udinese",
    // "Hellas Verona",
    // "Parma",
    // "Cagliari",
    //"Sassuolo",
    // Ligue 1
    "Paris Saint Germain",
    "Marseille",
    "Lyon",
    "Monaco",
    // "Nice",
    // "Rennes",
    // "Lille",
    "Lens",
    // "Saint-Étienne",
    // "Nantes",
    // "Bordeaux",
    // "Montpellier",
    // "Strasbourg",
    // "Toulouse",
    // "Brest",
    // "Angers",
    // "Reims",
    // " Metz",
    // "Amiens",
    // "Ajaccio",
    // Bundesliga
    "Bayern München",
    "Borussia Dortmund",
    "RB Leipzig",
    "Bayer Leverkusen",
    // "Borussia Mönchengladbach",
    // "Eintracht Frankfurt",
    // "Schalke 04",
    // "1899 Hoffenheim",
    // "1. FC Köln",
    // "VfB Stuttgart",
    // "Hertha BSC",
    // "Werder Bremen",
    // "FC Augsburg",
    // "FSV Mainz 05",
    // "Freiburg",
    // "Union Berlin",
    // "Bochum",
    // "Arminia Bielefeld",
    // "Greuther Fürth",
    // "Turkish Liga"
    "Galatasaray",
    "Fenerbahçe"
];

// SERIE A:  AC Milan, Atalanta, Bologna, Cagliari, Como, Fiorentina, Frosinone, Genoa, Inter, Juventus, Lazio, Lecce, Monza, Napoli, Parma, AS Roma, Sassuolo, Torino, Udinese, Venezia 



// BUNDESLIGA: Borussia Mönchengladbach, Bayer Leverkusen, SC Freiburg, VfB Stuttgart, FSV Mainz 05, Union Berlin, 1899 Hoffenheim, FC Augsburg, Werder Bremen, RB Leipzig, Borussia Dortmund, Eintracht Frankfurt, Bayern München -- FC Schalke 04 , SV Elversberg , and SC Paderborn 07



// PREMIER LEAGUE: Manchester United, Fulham, Ipswich, Liverpool, Newcastle, Arsenal, Everton, Brighton, Nottingham Forest, Bournemouth, Aston Villa, Brentford, Crystal Palace, Chelsea, Manchester City, Tottenham, ---Sunderland, Coventry, Hull, Leeds 



// LA LIGA: Athletic Club, Getafe, Real Betis, Celta Vigo, Alaves, Las Palmas, Sevilla, Osasuna, Leganes, Valencia, Barcelona, Real Sociedad, Rayo Vallecano, Real Madrid, Valladolid, Espanyol, Villarreal, Atletico Madrid --- Deportivo La Coruña , Elche CF , Levante UD , Málaga CF , and Racing Santander

export const watchedCountries = [
    // "Austria",
    "Belgium",
    // "Bosnia and Herzegovina",
    "Croatia",
    // "Czechia",
    "England",
    "France",
    "Germany",
    "Netherlands",
    "Norway",
    "Portugal",
    "Scotland",
    "Spain",
    "Sweden",
    "Switzerland",
    "Türkiye",
    "Argentina",
    "Brazil",
    "Colombia",
    "Ecuador",
    // "Paraguay",
    "Uruguay",
    // "Curaçao",
    // "Haiti",
    // "Panama",
    // "New Zealand",
    "Nigeria",
    // Nigeria,
    "Algeria",
    "Cape Verde",
    "DR Congo",
    "Ivory Coast",
    "Egypt",
    "Ghana",
    "Morocco",
    "Senegal",
    "South Africa",
    // "Tunisia",
    // "Australia",
    // "Iraq",
    // "Iran",
    "Japan",
    // "Jordan",
    "South Korea",
    // "Qatar",
    // "Saudi Arabia",
    // "Uzbekistan",
    // "Canada",
    "Mexico",
    // "United States"
];
